/**
 * The two files this tool writes, and the rule that lets them be read as one record.
 *
 * The tool itself cannot be imported -- it is a script with top-level await that fetches a
 * dump and writes files as a side effect of being loaded -- so this tests its output
 * instead. That is the useful subject anyway: what can go wrong here is the game's data
 * not resolving through the game's data, and a fixture cannot catch it.
 *
 * The counts are pinned, for the reason `spawnRules.unit.spec.js` gives about its own: they
 * are regenerated by hand from a dump, and a game update that retires a preset should fail
 * here rather than change a list quietly.
 */
import { describe, test, expect } from 'vitest';

import chain from '../../../refs/derived/furnitureChain.json' with { type: 'json' };
import rooms from '../../../refs/derived/roomCreator.json' with { type: 'json' };


describe('what the tool writes', () => {
    test('holds the game’s assets, in the counts the dump had', () => {
        expect(Object.keys(chain.furniture)).toHaveLength(310);
        expect(Object.keys(chain.classes)).toHaveLength(262);
        expect(Object.keys(chain.clusters)).toHaveLength(399);
        expect(Object.keys(chain.addresses)).toHaveLength(47);
    });

    /**
     * The rule that lets the two files be read as one record. A field in both is two
     * answers to one question about the game, with nothing to say which is right.
     */
    test('shares no field between the two files', () => {
        for (const [name, record] of Object.entries(rooms.clusters)) {
            for (const gate of Object.keys(record.gates ?? {})) {
                expect(Object.keys(chain.clusters[name]), `clusters.${name}.${gate}`)
                    .not.toContain(gate);
            }
        }

        for (const [name, record] of Object.entries(rooms.classes)) {
            for (const field of Object.keys(record)) {
                expect(Object.keys(chain.classes[name] ?? {}), `classes.${name}.${field}`)
                    .not.toContain(field);
            }
        }
    });

    /**
     * There is no third file. The furniture creator used to read one and now reads the
     * author's own exported ScriptableObjects an asset at a time -- so a regeneration that
     * quietly put one back would be reintroducing a trim nothing reads.
     */
    test('writes two files and not a third', async () => {
        const { readdir } = await import('node:fs/promises');
        const { fileURLToPath } = await import('node:url');
        const { dirname, join } = await import('node:path');

        const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
        const written = await readdir(join(root, 'refs', 'derived'));

        expect(written.sort()).toEqual(['furnitureChain.json', 'roomCreator.json']);
    });

    /** Asset names are the game's, not a URL's: four of them have a space in the name. */
    test('keeps a space in a name rather than the escape a listing gives it', () => {
        expect(chain.furniture['OldTelevisionLarge 1']).toBeTruthy();
        expect(Object.keys(chain.furniture).some((name) => name.includes('%20'))).toBe(false);
    });
});
