/**
 * The gates below the room class, against the game's own reference data.
 *
 * Fixtured only where a shipped cluster does not happen to exercise a branch. Everything
 * else runs against `refs/derived/roomCreator.json` and `refs/derived/furnitureChain.json`
 * as the app fetches them, for the reason `furnitureChain.unit.spec.js` gives: what can go
 * wrong here is the game's data not resolving through the game's data, and a fixture
 * cannot catch that.
 *
 * The counts are pinned. They are what the modal will show, they come from files
 * regenerated by hand from a dump, and a game update that retires a cluster or moves a
 * gate should fail here rather than change a list quietly.
 */
import { describe, test, expect } from 'vitest';

import {
    admits, admitted, gatesOf, closures, importantElements, surfaceFilters,
    unlitConfigurations, lightsFor, clustersFor, ADVISORY, CONTEXT,
} from './spawnRules.js';

import rooms from '../refs/derived/roomCreator.json' with { type: 'json' };
import chain from '../refs/derived/furnitureChain.json' with { type: 'json' };


describe('the reference data', () => {
    test('holds the game’s assets, in the counts the dump had', () => {
        expect(Object.keys(rooms.clusters)).toHaveLength(399);
        expect(Object.keys(rooms.configurations)).toHaveLength(79);
        expect(Object.keys(rooms.lighting)).toHaveLength(15);
        expect(Object.keys(rooms.filters)).toHaveLength(46);
    });

    /**
     * The rule that lets the two files be read as one record. If a field ever appears in
     * both, the two can disagree about the game and nothing would say which was right.
     */
    test('shares no field with furnitureChain.json', () => {
        for (const [name, record] of Object.entries(rooms.clusters)) {
            for (const gate of Object.keys(record.gates ?? {})) {
                expect(chain.clusters[name], name).toBeTruthy();
                expect(Object.keys(chain.clusters[name]), `clusters.${name}.${gate}`).not.toContain(gate);
            }
        }

        for (const [name, record] of Object.entries(rooms.classes)) {
            for (const field of Object.keys(record)) {
                expect(Object.keys(chain.classes[name] ?? {}), `classes.${name}.${field}`).not.toContain(field);
            }
        }
    });

    test('every name it carries is one the chain file also has', () => {
        for (const name of Object.keys(rooms.clusters)) expect(chain.clusters[name], name).toBeTruthy();
        for (const name of Object.keys(rooms.furniture)) expect(chain.furniture[name], name).toBeTruthy();
        for (const name of Object.keys(rooms.classes)) expect(chain.classes[name], name).toBeTruthy();
        for (const name of Object.keys(rooms.filters)) expect(chain.filters[name], name).toBeTruthy();
        for (const name of Object.keys(rooms.configurations)) expect(chain.roomConfigs[name], name).toBeTruthy();
    });

    /**
     * Absent means the table's value, never unset. A record that restated a default would
     * be dead weight in a file that exists to be small.
     */
    test('a gate absent from a record carries the default', () => {
        const gates = gatesOf(rooms, 'PicnicTable');

        expect(gates.limitToFloorRange).toBe(true);
        expect(gates.allowedOnFloorRange).toEqual({ x: -1, y: 0 });

        // Not stated on this cluster, so it comes from the table rather than as undefined.
        expect(gates.minimumWealth).toBe(rooms._gateDefaults.minimumWealth);
        expect(gates.limitToDistricts).toBe(rooms._gateDefaults.limitToDistricts);

        for (const [name, record] of Object.entries(rooms.clusters)) {
            for (const [gate, value] of Object.entries(record.gates ?? {})) {
                expect(value, `${name}.${gate} restates the default`)
                    .not.toEqual(rooms._gateDefaults[gate]);
            }
        }
    });
});


describe('a gate nobody answered', () => {
    test('is reported rather than treated as a refusal', () => {
        const result = admits(rooms, 'PicnicTable', {});

        expect(result.verdict).toBe('possible');
        expect(result.failures).toEqual([]);
        expect(result.unanswered).toContain('floor');
    });

    test('is answered once the author states it', () => {
        expect(admits(rooms, 'PicnicTable', { floor: 0 }).verdict).toBe('possible');
        expect(admits(rooms, 'PicnicTable', { floor: 0 }).unanswered).not.toContain('floor');
    });

    test('treats floor 0 and wealth 0 as answers, not as absence', () => {
        expect(admits(rooms, 'PicnicTable', { floor: 0 }).unanswered).not.toContain('floor');
        expect(admits(rooms, 'PicnicTable', { floor: null }).unanswered).toContain('floor');
        expect(admits(rooms, 'PicnicTable', { floor: undefined }).unanswered).toContain('floor');
    });
});


describe('the worked example', () => {
    /**
     * `PicnicTable` is the server plan's own example, and it is here because it is
     * awkward: it conflicts on floor range, which is what forces it to be cloned rather
     * than patched when the room is indoors above ground.
     */
    test('PicnicTable is refused above ground, and says why', () => {
        const result = admits(rooms, 'PicnicTable', { floor: 3 });

        expect(result.verdict).toBe('no');
        expect(result.failures).toHaveLength(1);
        expect(result.failures[0].gate).toBe('floor');
        expect(result.failures[0].reason).toBe(
            'It is limited to floors -1 to 0, and this room is on 3.');
    });

    test('its closure is the one bench, which is why the preset needs patching too', () => {
        expect(closures(chain).PicnicTable).toEqual(['PicnicBench']);

        expect(importantElements(chain, 'PicnicTable')).toEqual([
            { class: '1x1PicnicBench', presets: ['PicnicBench'] },
        ]);
    });
});


describe('every gate that fails, not the first', () => {
    /**
     * The opposite of `checkFurniture`, where the stages are a chain and the first failure
     * contains the rest. These are independent conditions on the room being designed, so
     * fixing the floor does not tell the author the wealth is also wrong.
     */
    test('reports each independently', () => {
        const fixture = {
            _gateDefaults: rooms._gateDefaults,
            clusters: {
                Fussy: {
                    gates: {
                        limitToFloor: true,
                        allowedOnFloor: 0,
                        minimumWealth: 0.8,
                        allowedInOpenPlan: 1,
                    },
                },
            },
        };

        const result = admits(fixture, 'Fussy', { floor: 4, wealth: 0.1, openPlan: true });

        expect(result.verdict).toBe('no');
        expect(result.failures.map((f) => f.gate).sort()).toEqual(['floor', 'openPlan', 'wealth']);
    });
});


describe('open plan', () => {
    const fixture = (allowedInOpenPlan) => ({
        _gateDefaults: rooms._gateDefaults,
        clusters: { X: { gates: { allowedInOpenPlan } } },
    });

    test('1 keeps it out of an open plan room', () => {
        expect(admits(fixture(1), 'X', { openPlan: true }).verdict).toBe('no');
        expect(admits(fixture(1), 'X', { openPlan: false }).verdict).toBe('possible');
    });

    test('2 places it only in one', () => {
        expect(admits(fixture(2), 'X', { openPlan: true }).verdict).toBe('possible');
        expect(admits(fixture(2), 'X', { openPlan: false }).verdict).toBe('no');
    });

    test('0 takes either', () => {
        expect(admits(fixture(0), 'X', { openPlan: true }).verdict).toBe('possible');
        expect(admits(fixture(0), 'X', { openPlan: false }).verdict).toBe('possible');
        expect(admits(fixture(0), 'X', {}).unanswered).not.toContain('openPlan');
    });
});


describe('what is reported rather than applied', () => {
    /**
     * The three address-kind flags are the ones this is really about. Applying them as an
     * AND would drop furniture that does appear -- see furnitureChain.js, and ADVISORY.
     */
    /**
     * The evidence, pinned, because this is the gate a future reader is most likely to
     * decide is safe to apply. These 16 clusters set all three flags false and are not
     * disabled, and every one of them is furniture the game visibly places -- mailboxes
     * are in the lobby of every apartment building. Any reading that treats the flags as
     * a hard filter on the address kind makes all 16 unplaceable.
     */
    test('16 enabled clusters allow none of the three address kinds', () => {
        const off = (name) => {
            const gates = gatesOf(rooms, name);
            return !gates.allowInCompanies && !gates.allowInResidential && !gates.allowOnStreets;
        };

        const enabled = Object.keys(rooms.clusters)
            .filter((name) => off(name) && !chain.clusters[name].disable)
            .sort();

        expect(enabled).toEqual([
            'BasementSteps', 'CityHallExterior', 'LobbyOutsideAddressDoor',
            'Mailboxes10', 'Mailboxes100', 'Mailboxes20', 'Mailboxes25', 'Mailboxes35',
            'Mailboxes45', 'Mailboxes50', 'Mailboxes60', 'Mailboxes75',
            'StairwellWallLamps', 'StairwellWallLampsHotel',
            'TownhouseExterior', 'TownhouseExteriorInv',
        ]);

        // And none of them is refused, however fully the context is stated.
        for (const name of enabled) {
            const result = admits(rooms, name, {
                floor: 0, wealth: 0.5, grub: 0.5, openPlan: false, inhabitants: true, residences: 4,
            });
            expect(result.failures.map((f) => f.gate), name).not.toContain('allowInCompanies');
        }
    });

    test('the address-kind flags never refuse anything', () => {
        for (const flag of ['allowInCompanies', 'allowInResidential', 'allowOnStreets']) {
            expect(Object.keys(ADVISORY)).toContain(flag);
        }

        const fixture = {
            _gateDefaults: rooms._gateDefaults,
            clusters: {
                X: {
                    gates: {
                        allowInCompanies: false, allowInResidential: false, allowOnStreets: false,
                    },
                },
            },
        };

        const result = admits(fixture, 'X', { floor: 0, wealth: 0.5, openPlan: false });

        expect(result.verdict).toBe('possible');
        expect(result.advisory.map((entry) => entry.gate).sort())
            .toEqual(['allowInCompanies', 'allowInResidential', 'allowOnStreets']);
    });

    test('no advisory field is also evaluated as a gate', () => {
        for (const field of Object.keys(ADVISORY)) expect(CONTEXT).not.toContain(field);
    });

    test('every shipped cluster survives a fully stated context on the advisory fields alone', () => {
        // Nothing in ADVISORY may turn a `possible` into a `no`, whatever it is set to.
        const full = { floor: 0, wealth: 0.5, grub: 0.5, openPlan: false, inhabitants: true, residences: 4, district: 'Unknown' };

        for (const name of Object.keys(rooms.clusters)) {
            const failed = admits(rooms, name, full).failures.map((f) => f.gate);
            for (const gate of failed) expect(Object.keys(ADVISORY), `${name}.${gate}`).not.toContain(gate);
        }
    });
});


describe('across every shipped cluster', () => {
    test('an empty context refuses nothing', () => {
        const { refused } = admitted(rooms, Object.keys(rooms.clusters), {});
        expect(refused).toEqual([]);
    });

    test('a ground floor room at middling wealth is refused by four gates, and not by floor', () => {
        const { possible, refused } = admitted(rooms, Object.keys(rooms.clusters), {
            floor: 0, wealth: 0.5, grub: 0.5, openPlan: false, inhabitants: true, residences: 4,
        });

        expect(possible.length + refused.length).toBe(399);

        // Pinned: the gates that can speak at all on this context. `floor` is absent
        // because every floor gate in the shipped data admits the ground floor -- even
        // `PicnicTable`, whose range is -1 to 0. District is unstated here, so a cluster
        // limited to districts comes back unanswered rather than refused.
        const gates = [...new Set(refused.flatMap((entry) => entry.failures.map((f) => f.gate)))].sort();
        expect(gates).toEqual(['grub', 'openPlan', 'residences', 'wealth']);
    });

    test('the same room three storeys up loses the clusters kept to the ground', () => {
        const context = { floor: 3, wealth: 0.5, grub: 0.5, openPlan: false, inhabitants: true, residences: 4 };
        const ground = admitted(rooms, Object.keys(rooms.clusters), { ...context, floor: 0 });
        const upstairs = admitted(rooms, Object.keys(rooms.clusters), context);

        expect(upstairs.possible.length).toBeLessThan(ground.possible.length);

        const byFloor = upstairs.refused.filter((entry) => entry.failures.some((f) => f.gate === 'floor'));
        expect(byFloor.map((entry) => entry.name)).toContain('PicnicTable');
    });

    test('every reason names the gate’s own numbers', () => {
        const { refused } = admitted(rooms, Object.keys(rooms.clusters), {
            floor: 7, wealth: 0.1, grub: 0.9, openPlan: true, inhabitants: false, residences: 0,
        });

        expect(refused.length).toBeGreaterThan(0);

        for (const entry of refused) {
            for (const failure of entry.failures) {
                expect(failure.reason, `${entry.name}.${failure.gate}`).toMatch(/^It /);
                expect(failure.reason.endsWith('.'), failure.reason).toBe(true);
            }
        }
    });
});


describe('the closure', () => {
    test('covers every cluster, and six shipped ones resolve to nothing', () => {
        const all = closures(chain);
        expect(Object.keys(all)).toHaveLength(399);

        // `NullCluster` is empty on purpose and is not one of the six the server plan
        // names, which is why it is listed apart rather than folded in.
        const empty = Object.entries(all).filter(([, presets]) => presets.length === 0).map(([name]) => name);

        expect(empty.sort()).toEqual([
            'HiFiSystem', 'JunkCupboard', 'JunkLargeRetail', 'ModernWoodCabinet',
            'NullCluster', 'SentryGunRightCorner', 'SentryGunRightCornerResidential',
        ]);
    });

    test('never names a preset the chain file does not have', () => {
        for (const [name, presets] of Object.entries(closures(chain))) {
            for (const preset of presets) expect(chain.furniture[preset], `${name} -> ${preset}`).toBeTruthy();
        }
    });
});


describe('what furnishes a shipped room', () => {
    test('answers with the clusters whose filters reach the configuration’s class', () => {
        const ballroom = clustersFor(chain, 'Ballroom');
        const ballroomFilters = new Set(Object.entries(chain.filters)
            .filter(([, classes]) => classes.includes('Ballroom')).map(([name]) => name));

        expect(ballroom).toHaveLength(55);
        expect(ballroomFilters.size).toBeGreaterThan(0);

        for (const name of ballroom) {
            expect(chain.clusters[name].filters.some((filter) => ballroomFilters.has(filter)), name).toBe(true);
        }

        // And nothing outside it: a cluster no filter of this class names would be a room
        // furnished with things it has never been seen holding.
        for (const [name, cluster] of Object.entries(chain.clusters)) {
            if (ballroom.includes(name) || cluster.disable) continue;
            expect(cluster.filters.some((filter) => ballroomFilters.has(filter)), name).toBe(false);
        }
    });

    /**
     * The one gate of `blockedBy` applied here besides the filters. A disabled cluster is
     * refused before its filters are read, so copying one into a room writes a patch the
     * game will not act on.
     */
    test('leaves out the disabled clusters, which never place', () => {
        const lobby = clustersFor(chain, 'Lobby');

        expect(lobby).toHaveLength(52);
        for (const name of lobby) expect(chain.clusters[name].disable, name).toBe(false);

        // Every mailbox set in the game is disabled, and they name Lobby's filters -- so
        // this is the case that would go unnoticed if the gate were dropped.
        expect(lobby).not.toContain('Mailboxes30');
        expect(chain.clusters.Mailboxes30.disable).toBe(true);
    });

    /**
     * Not an error, and worth pinning: an author copying one of these gets a room the
     * generator furnishes with nothing whatever the button does, and the pane says so
     * rather than appearing to have done nothing.
     */
    test('three shipped configurations are in no cluster’s filters at all', () => {
        const barren = Object.keys(chain.roomConfigs).filter((name) => !clustersFor(chain, name).length);
        expect(barren.sort()).toEqual(['Atrium', 'Null', 'RooftopVent']);
    });

    test('says nothing for a configuration that is not in the game', () => {
        expect(clustersFor(chain, 'PicnicAreaRC')).toEqual([]);
        expect(clustersFor(chain, '')).toEqual([]);
        expect(clustersFor(null, 'Ballroom')).toEqual([]);
    });

    /** The copy button ticks these, so every one of them has to be a row the pane draws. */
    test('every configuration’s clusters are ones the gate file also carries', () => {
        for (const configuration of Object.keys(chain.roomConfigs)) {
            for (const name of clustersFor(chain, configuration)) {
                expect(rooms.clusters[name], `${configuration} -> ${name}`).toBeTruthy();
            }
        }
    });
});


describe('surfaces', () => {
    /**
     * Rule 4 of the server plan, derived rather than taken on trust: a filter that supplies
     * materials and is named by no cluster or preset is safe to join, and one that gates
     * furniture as well would bring that furniture into the room.
     */
    test('splits the material filters into safe and furniture-bearing', () => {
        const surfaces = surfaceFilters(rooms, chain);

        expect(surfaces.walls.safe).toEqual([
            'BrickWall', 'Lino', 'OldBrick', 'PlainWall', 'WallpaperHome', 'WoodenPanels',
        ]);
        expect(surfaces.floor.safe).toEqual([
            'Carpet', 'CoatedConcrete', 'ConcreteFloor', 'Grass', 'Lino',
            'WoodenFlooring', 'WoodenFlooringFancy',
        ]);
        expect(surfaces.ceiling.safe).toEqual(['CeilingTiles', 'PlasterCeiling']);

        // The one the plan calls out by name: picking it for walls admits its furniture.
        expect(surfaces.walls.alsoGatesFurniture).toContain('CorporateLobby');
    });

    test('no filter is both safe and furniture-bearing for one surface', () => {
        const surfaces = surfaceFilters(rooms, chain);

        for (const [surface, entry] of Object.entries(surfaces)) {
            for (const name of entry.safe) {
                expect(entry.alsoGatesFurniture, `${surface}.${name}`).not.toContain(name);
            }
        }
    });
});


describe('lighting', () => {
    test('names the configurations that would get no ceiling light', () => {
        expect(unlitConfigurations(rooms)).toEqual([
            'Alley', 'Backstreet', 'Ballroom', 'FathomsYard', 'Joiner', 'Null', 'Park',
            'Path', 'Rooftop', 'RooftopBar', 'RooftopGeneral', 'RooftopVent', 'Street',
            'StreetFrontage',
        ]);
    });

    test('65 of the 79 shipped configurations are lit', () => {
        const unlit = unlitConfigurations(rooms).length;
        expect(Object.keys(rooms.configurations).length - unlit).toBe(65);
    });

    test('says which presets accept a configuration, so one can be patched', () => {
        const lights = lightsFor(rooms, 'Atrium');

        expect(lights.length).toBeGreaterThan(0);
        for (const name of lights) expect(rooms.lighting[name].rooms).toContain('Atrium');

        // An unlit one has none, which is the whole reason the modal has a lighting step.
        expect(lightsFor(rooms, 'Ballroom')).toEqual([]);
    });
});
