/**
 * The furniture chain, against the base game's own floors and reference data.
 *
 * Nothing here is fixtured. The chain data is the file the app fetches and the floors are
 * the 93 blueprints under refs/floors, so what these assert is that the game's data
 * resolves through the game's data -- which is the only thing that can go wrong here. The
 * resolver has no state and one input.
 *
 * The counts are pinned deliberately. They are what the app shows, they come from a file
 * regenerated by hand from a dump of the game, and a game update that changes a room
 * class or retires a cluster should be a failing test rather than a quietly different
 * list. When one moves, check the change is the game's before repinning it.
 */
import { describe, test, expect, beforeAll } from 'vitest';

import { parseFloor, getWall, tileForNode, AXIS_X, AXIS_Y } from './floorModel.js';
import {
    loadFurnitureChain, furnitureChain, furnitureAt, explainFurniture,
    furniturePresetNames, furniturePresetSections, clusterWarnings, UNAPPLIED_GATES,
} from './furnitureChain.js';
import { overlayChain } from './furnitureOverlay.js';
import {
    WALL_RULE, BLOCKING_DIRECTION, WALL_SECTION_CLASS, UNREADABLE_TAGS,
} from './furnitureRules.js';

// Read here rather than in the resolver, which deliberately no longer consults it: the
// divider test asserts that what this table calls a blank is counted all the same.
import wallPresetKinds from '../../../refs/authored/wallPresetKinds.json' with { type: 'json' };

// The wall ids a blueprint stores are indices into this, so a `walls` key that is not in
// it is one no blueprint could ever ask about.
import soDoorPairIds from '../../../refs/generated/soDoorPairIds.json' with { type: 'json' };

let chain;
let hotel;

const blueprint = async (name) =>
    parseFloor(await (await fetch(`/refs/floors/blueprints/${name}.json`)).json());

/** The first node of the first room whose preset is `roomType`. */
function findRoom(model, roomType) {
    const room = model.rooms.find((entry) => entry.preset === roomType);
    if (!room) throw new Error(`no ${roomType} on this floor`);

    const index = model.nodes.findIndex((node) => node
        && node.addressIndex === room.addressIndex && node.roomIndex === room.roomIndex);

    return { x: index % 21, y: Math.floor(index / 21) };
}

beforeAll(async () => {
    chain = await loadFurnitureChain();
    hotel = await blueprint('Hotel_GroundFloor');
});


describe('the reference data', () => {
    test('loads, and is the same object on a second call', async () => {
        expect(chain).toBeTruthy();
        expect(furnitureChain()).toBe(chain);
        expect(await loadFurnitureChain()).toBe(chain);
    });

    test('holds the game’s assets, in the counts the dump had', () => {
        expect(Object.keys(chain.addresses)).toHaveLength(47);
        expect(Object.keys(chain.roomConfigs)).toHaveLength(79);
        expect(Object.keys(chain.clusters)).toHaveLength(399);
        expect(Object.keys(chain.furniture)).toHaveLength(310);
        expect(Object.keys(chain.classes)).toHaveLength(262);
        expect(Object.keys(chain.walls)).toHaveLength(27);
    });

    /**
     * The wall rules, pinned as counts because they are the bulk of what the file now
     * carries and a regeneration that came out short is the failure it is most exposed
     * to. 697 is the game's 841 less the 135 `canFeature` rules, which score rather than
     * gate, and the 9 `securityDoorDivider` ones, which read the floor's air ducts.
     */
    test('carries the wall rules, in the counts the game’s classes hold', () => {
        const classes = Object.values(chain.classes);
        const rules = classes.flatMap((entry) => entry.wallRules ?? []);

        expect(classes.filter((entry) => entry.wallRules).length).toBe(230);
        expect(rules).toHaveLength(697);
        expect(classes.reduce((total, entry) => total + (entry.unchecked ?? 0), 0)).toBe(9);

        // Names, not indices. The whole reason these had to come from a decompiled source
        // is that the obvious enum table for them is the wrong enum -- see furnitureRules.
        for (const rule of rules) {
            expect(WALL_RULE, rule.tag).toContain(rule.tag);
            expect(BLOCKING_DIRECTION, rule.dir).toContain(rule.dir);
            expect(typeof rule.must).toBe('boolean');
        }

        // No rule survives that this cannot answer.
        for (const rule of rules) expect(UNREADABLE_TAGS.has(rule.tag)).toBe(false);
    });

    test('every wall preset is a section class, and every id is one a blueprint stores', () => {
        for (const [id, wall] of Object.entries(chain.walls)) {
            expect(WALL_SECTION_CLASS, id).toContain(wall.section);
            expect(soDoorPairIds[id], id).toBeTruthy();
        }

        // The three the tags turn on, spot-checked against the assets they come from:
        // a doorway is an entrance, a divider is an entrance that is one, and a
        // NothingWall is a large window that is also a fence. The last looks wrong and is
        // not -- it is why a blank counts, and what it matches when a rule asks.
        expect(chain.walls['7']).toEqual({ section: 'entrance' });
        expect(chain.walls['5']).toEqual({ section: 'entrance', divider: true });
        expect(chain.walls['11']).toEqual({ section: 'windowLarge', fence: true });
    });

    test('every room a wall rule names is a configuration that exists', () => {
        for (const [name, entry] of Object.entries(chain.classes)) {
            for (const rule of entry.wallRules ?? []) {
                if (!rule.room) continue;
                expect(chain.roomConfigs[rule.room], `${name} -> ${rule.room}`).toBeTruthy();
            }
        }
    });

    test('every room configuration names a room type and a room class', () => {
        for (const [name, config] of Object.entries(chain.roomConfigs)) {
            expect(config.roomType, name).toBeTruthy();
            expect(config.roomClass, name).toBeTruthy();
        }
    });

    test('every class a cluster element names is a class that exists', () => {
        const classes = new Set(Object.keys(chain.classes));

        for (const [name, cluster] of Object.entries(chain.clusters)) {
            for (const element of cluster.elements) {
                if (element.class) expect(classes.has(element.class), `${name} -> ${element.class}`).toBe(true);
            }
        }
    });

    /**
     * An asset is keyed by what it is called, and four of the game's have a space in the
     * name. The generator used to key them by the percent-encoded href it found them at,
     * which made `OldTelevisionLarge%201` a preset nothing could look up -- and only over
     * HTTP, so the file disagreed with itself depending on how the tool had been run. See
     * `readType` in tools/buildFurnitureChain.js.
     *
     * Asserted over the whole file rather than on those four, because the next asset with
     * a space in its name should fail here rather than ship.
     */
    test('names assets as the game calls them, not as a URL spells them', () => {
        const named = ['clusters', 'furniture', 'classes', 'filters', 'roomConfigs', 'addresses'];
        const spaced = [];

        for (const block of named) {
            for (const name of Object.keys(chain[block])) {
                expect(name, `${block}.${name}`).not.toMatch(/%[0-9A-Fa-f]{2}/);
                if (name.includes(' ')) spaced.push(`${block}.${name}`);
            }
        }

        // The four that carried the escape, so a regeneration that drops them is a
        // failure here rather than a silently shorter list.
        expect(spaced.sort()).toEqual([
            'clusters.DrinksCoolersX2 1',
            'clusters.MarketStandX2 2',
            'clusters.SupermarketFrigeUnitsX3 2',
            'furniture.OldTelevisionLarge 1',
        ]);
    });
});


describe('resolving a node', () => {
    test('an office is answered once per address preset competing for the unit', async () => {
        const model = await blueprint('Eden_OfficeFloor01');
        const at = findRoom(model, 'OfficeSpace');
        const result = furnitureAt(chain, model, at.x, at.y);

        expect(result.layout).toBe('OfficeHighrise');
        expect(result.roomType).toBe('OfficeSpace');
        expect(result.reason).toBeNull();

        // Both presets compatible with OfficeHighrise, and they disagree about what an
        // OfficeSpace is -- which is the whole reason the result is grouped.
        expect(result.groups.map((group) => group.address)).toEqual(['HighriseOffice', 'Laboratory']);
        expect(result.groups.map((group) => group.roomClass)).toEqual(['OfficeSpace', 'Laboratory']);
        expect(result.groups[0].config).toBe('Office');
        expect(result.groups[1].config).toBe('Laboratory');
    });

    test('a group lists furniture under the slot class it fills', async () => {
        const model = await blueprint('Eden_OfficeFloor01');
        const at = findRoom(model, 'OfficeSpace');
        const [office] = furnitureAt(chain, model, at.x, at.y).groups;

        const cubicles = office.classes.find((row) => row.name === '1x1OfficeCubicle');
        expect(cubicles.presets.map((preset) => preset.name))
            .toEqual(['ModernOfficeCubicle', 'OfficeCubicle']);

        // The count is distinct presets across every slot, not the sum of the rows: one
        // preset can fill several classes, and it is one object either way.
        const named = new Set(office.classes.flatMap((row) => row.presets.map((p) => p.name)));
        expect(office.count).toBe(named.size);
        expect(office.count).toBeLessThan(
            office.classes.reduce((total, row) => total + row.presets.length, 0));
    });

    /**
     * Size and walls both gate, and they gate independently -- so the size test holds
     * the walls still.
     *
     * ChemPlantGroundFloor1 has three `IndustrialLobby` rooms, one of 15 nodes and two of
     * 4. Comparing a square with two walls in each isolates size: everything else the
     * chain reads is identical between them.
     */
    test('room size gates what fits, with the walls held still', async () => {
        const model = await blueprint('ChemPlantGroundFloor1');

        // Two walls each, in rooms of 15 nodes and of 4.
        const large = furnitureAt(chain, model, 9, 15);
        const small = furnitureAt(chain, model, 12, 13);

        expect([large.roomSize, large.walls]).toEqual([15, 2]);
        expect([small.roomSize, small.walls]).toEqual([4, 2]);

        expect(large.groups[0].count).toBe(5);
        expect(small.groups[0].count).toBe(2);

        // The larger room admits everything the smaller does. Every gate size touches is
        // a minimum or a maximum, and nothing here sets a maximum a 15-node room exceeds.
        const names = (result) => new Set(
            result.groups[0].classes.flatMap((row) => row.presets.map((preset) => preset.name)));

        const admitted = names(large);
        for (const name of names(small)) expect(admitted.has(name), name).toBe(true);
    });

    /**
     * Walls gate per square, by how many there are and by what they are.
     *
     * Three squares of one 28-node `OfficeSpace`, so the room is held still and the walls
     * are the only thing that moves. They differ in both ways at once, which is the point:
     *
     *   middle  no walls
     *   edge    one wall, and it is a doorway
     *   corner  two walls, and both are large windows
     *
     * More walls is therefore **not** more furniture, and this used to assert that it was.
     * The edge has a wall the middle has not and offers less than the middle does, because
     * a doorway on a square bars every class that takes the square up -- 179 of the game's
     * 262. That is `occupiesTile` at `GenerationController.cs:4663`.
     */
    test('what a square offers depends on the kind of wall, not only the count', async () => {
        const model = await blueprint('Eden_OfficeFloor01');

        const middle = furnitureAt(chain, model, 4, 12);
        const edge = furnitureAt(chain, model, 4, 11);
        const corner = furnitureAt(chain, model, 3, 11);

        expect([middle.roomSize, edge.roomSize, corner.roomSize]).toEqual([28, 28, 28]);
        expect([middle.walls, edge.walls, corner.walls]).toEqual([0, 1, 2]);

        // Open floor takes almost nothing: 38 of the room's slot classes want a wall, and
        // what is left is what can stand free in the middle of a room.
        expect(middle.groups[0].count).toBe(4);
        expect(middle.groups[0].offWall).toEqual({ needsWall: 38, needsOpen: 0, wrongWalls: 0 });

        // The edge has a wall, so 28 of those 38 now have the one they wanted -- and 27
        // are turned away again by what that wall is rather than by how many there are.
        expect(edge.groups[0].count).toBe(4);
        expect(edge.groups[0].offWall).toEqual({ needsWall: 10, needsOpen: 0, wrongWalls: 27 });

        expect(corner.groups[0].count).toBe(19);
        expect(corner.groups[0].offWall).toEqual({ needsWall: 0, needsOpen: 0, wrongWalls: 21 });

        const classes = (result) => result.groups[0].classes;

        // The middle is not a subset of the edge. An easel and a cubicle can stand on open
        // floor and not on a square with a doorway on it.
        const walled = new Set(classes(edge).map((row) => row.name));
        expect(classes(middle).filter((row) => !walled.has(row.name)).map((row) => row.name))
            .toEqual(['1x1Easel', '1x1OfficeCubicle']);

        // Nothing hangs on a wall that is not there -- and nothing hangs on these walls
        // either, because a picture over a window is what `tall` and `wallPiece` exist to
        // prevent (`:4667`). The corner has two walls and no wall piece among them.
        for (const result of [middle, edge, corner]) {
            expect(classes(result).some((row) => row.wallPiece), `${result.walls} walls`).toBe(false);
        }
    });

    /**
     * The two security door classes, which carry a rule no blueprint can answer.
     *
     * `securityDoorDivider` reads the room's `securityDoors` rule, the address through the
     * wall, whether that room holds a stairwell, the doors already placed on the floor and
     * -- above the ground floor -- whether the building's air ducts reach a basement. Those
     * rules are dropped when the reference data is built and counted instead, so the two
     * classes are neither offered as possible nor refused.
     */
    test('a class gated on something unreadable is counted, not decided', async () => {
        const model = await blueprint('Eden_OfficeFloor01');
        const group = furnitureAt(chain, model, 4, 11).groups[0];

        expect(group.unchecked).toBe(2);
        expect(group.classes.map((row) => row.name))
            .toEqual(expect.arrayContaining(['2x1SecurityDoor', '3x1SecurityDoor']));
    });

    /**
     * A blank is a wall as far as the count goes.
     *
     * `NothingWall`, `NothingEntrance` and the three dividers draw as openings with no
     * structure, and `wallPresetKinds.json` calls them blanks for that reason. The
     * generator does not: it compares `newNode.walls.Count` raw and gives those presets no
     * special handling, so a square beside a divider is a square against a wall.
     *
     * Pinned on a square whose two walls are one of each kind, so that a reading which
     * counted only the solid one would come back 1 rather than merely counting something
     * else twice.
     */
    test('a divider counts toward the wall count, as the game counts it', async () => {
        const model = await blueprint('ChemPlantGroundFloor1');

        // A blueprint stores a wall as a string index into `DoorPairPreset`, not a number.
        const presets = [
            getWall(model, 11, 13, AXIS_X)?.preset,  // InteriorDoorway
            getWall(model, 12, 12, AXIS_Y)?.preset,  // DividerEndLeft, a blank
        ];
        expect(presets).toEqual(['7', '5']);
        expect(wallPresetKinds['5']).toBe('blank');

        expect(furnitureAt(chain, model, 12, 13).walls).toBe(2);
    });

    /**
     * The stairwell gate, which reaches a square further than its name suggests.
     *
     * With `allowedOnStairwell` off -- 244 of the game's 262 classes -- the square must be
     * clear of stairwell tiles *and so must its four orthogonal neighbours*
     * (`GenerationController.cs:4575-4591`). So the ring of squares around a stairwell is
     * a different question from the ones beyond it, and pinning only the tile itself would
     * pass a reading that missed the neighbours entirely.
     */
    test('a stairwell empties its own tile and the squares beside it', async () => {
        const model = await blueprint('Hotel_GroundFloor');

        // Two squares of the hotel's Kitchen, both with two walls, so the count and the
        // room are held still and the stairwell next door is the only difference.
        const beside = furnitureAt(chain, model, 3, 8);
        const away = furnitureAt(chain, model, 3, 3);

        expect(tileForNode(model, 3, 8).isStairwell).toBe(false);
        expect(tileForNode(model, 3, 9).isStairwell).toBe(true);

        expect([beside.walls, away.walls]).toEqual([2, 2]);
        expect(beside.groups[0].count).toBe(10);
        expect(away.groups[0].count).toBe(43);

        // And the reason is the neighbour rather than anything about the square itself,
        // which is the half of this gate a reading of `allowedOnStairwell` alone misses.
        expect(explainFurniture(chain, model, 3, 3, 'BreakerBox').groups[0].verdict)
            .toBe('possible');

        expect(explainFurniture(chain, model, 3, 8, 'BreakerBox').groups[0].reason)
            .toContain('not allowed on a stairwell tile, nor on any square beside one');
    });

    /**
     * Two flags that bar a class by what is on the square rather than by a rule it states.
     *
     * `occupiesTile` refuses a square carrying a doorway that is not a divider (`:4663`),
     * and `tall` or `wallPiece` refuses one carrying a window of either size (`:4667`).
     * Between them they are 179 and 80 of the 262 classes, so they move more furniture
     * than any single wall rule does.
     */
    test('a doorway on a square keeps furniture off it, and a window keeps pictures off', async () => {
        const model = await blueprint('Eden_OfficeFloor01');

        const doorway = explainFurniture(chain, model, 4, 11, 'WaterCooler').groups[0];
        expect(doorway.stage).toBe('wallRules');
        expect(doorway.reason).toContain('takes up the whole square, and this one has a doorway');

        // The corner's two walls are both large windows, so nothing that would stand in
        // front of one is offered there -- however many walls it has to hang on.
        const corner = furnitureAt(chain, model, 3, 11).groups[0];
        expect(corner.classes.some((row) => row.wallPiece)).toBe(false);
    });

    test('the address gate is applied per group, not to a shared pool', () => {
        // Two groups over one room can differ by more than their room class: a preset
        // carrying `onlyAllowInFollowing` or `banInFollowing` is admitted to one and not
        // the other. The gate has to be real in this data for that to mean anything.
        const gated = Object.values(chain.furniture)
            .filter((furniture) => furniture.onlyIn?.length || furniture.bannedIn?.length);

        expect(gated.length).toBeGreaterThan(0);
    });
});


describe('when there is nothing to list', () => {
    test('an outdoor address says so rather than reporting an empty room', () => {
        const outside = hotel.nodes.find((node) => node
            && hotel.addresses[node.addressIndex]?.layoutConfiguration === 'Outside');
        expect(outside).toBeTruthy();

        const index = hotel.nodes.indexOf(outside);
        const result = furnitureAt(chain, hotel, index % 21, Math.floor(index / 21));

        expect(result.groups).toEqual([]);
        expect(result.reason).toMatch(/outdoor layout/);
    });

    test('a layout no address preset is compatible with names the lobby fallback', async () => {
        // FathomsLobby is the game's own -- no AddressPreset lists it in `compatible`,
        // which is the condition `No address preset shortlist for …` is logged for.
        const model = await blueprint('ShantyTown_Basement01');
        const address = model.addresses.findIndex(
            (entry) => entry.layoutConfiguration === 'FathomsLobby');
        expect(address).toBeGreaterThanOrEqual(0);

        const index = model.nodes.findIndex((node) => node && node.addressIndex === address);
        const result = furnitureAt(chain, model, index % 21, Math.floor(index / 21));

        expect(result.groups).toEqual([]);
        expect(result.reason).toMatch(/falls back to its lobby preset/);
    });

    test('no data, no model and no node each give nothing rather than throwing', () => {
        expect(furnitureAt(null, hotel, 10, 10)).toBeNull();
        expect(furnitureAt(chain, null, 10, 10)).toBeNull();
        expect(furnitureAt(chain, hotel, -1, -1)).toBeNull();
        expect(furnitureAt(chain, hotel, 99, 99)).toBeNull();
    });
});


describe('across every base game floor', () => {
    /**
     * The coverage claim this feature rests on: walk every floor, every address and every
     * room, and resolve one node of each. Nothing may throw, and every room that ought to
     * produce a list must.
     *
     * The seven that do not are pinned by name rather than counted, because each is a
     * different statement. Six are outdoor layouts, which are not furnished from a room
     * class at all. The seventh is `FathomsLobby`, which no address preset lists as
     * compatible -- the game's own data, and exactly the condition its lobby fallback
     * exists for. An eighth appearing means a layout has stopped resolving, which is a
     * thing to look at rather than a number to update.
     */
    test('every room on every base game floor resolves, bar the seven that cannot', async () => {
        const index = await (await fetch('/refs/floors/index.json')).json();
        const reasons = new Map();
        let resolved = 0;

        for (const name of index.blueprints) {
            const model = await blueprint(name);

            const seen = new Set();
            for (const [position, node] of model.nodes.entries()) {
                if (!node) continue;

                const key = `${node.addressIndex}:${node.roomIndex}`;
                if (seen.has(key)) continue;
                seen.add(key);

                const result = furnitureAt(chain, model, position % 21, Math.floor(position / 21));
                if (!result) continue;

                if (result.groups.length > 0) resolved++;
                else reasons.set(`${result.layout} / ${result.roomType}`, result.reason);
            }
        }

        expect(resolved).toBe(1399);
        expect([...reasons.keys()].sort()).toEqual([
            'FathomsLobby / FathomsLobby',
            'FathomsYard / FathomsYard',
            'Outside / Null',
            'Park / Park',
            'Path / Path',
            'StreetFrontage / StreetFrontage',
            'Yard / Yard',
        ]);

        // Only one of the seven is the lobby fallback; the rest are outdoors. Asserted
        // so a layout quietly moving from one explanation to the other is caught.
        expect([...reasons.values()].filter((reason) => /outdoor layout/.test(reason)))
            .toHaveLength(6);

        // 93 blueprints read off disk and 1,406 rooms resolved. Comfortably under this
        // on a warm run and not always under the 5 s default on a cold one, which is a
        // slow test rather than a broken one.
    }, 30_000);
});


test('the gates it cannot apply are the ones the panel names', () => {
    expect(UNAPPLIED_GATES).toContain('design style');
    expect(UNAPPLIED_GATES).toContain('district');
    expect(UNAPPLIED_GATES).toContain('wealth');
});


/*
 * Why one preset cannot spawn on one square.
 *
 * `explainFurniture` and `furnitureAt` are the same walk -- `checkFurniture` -- run over
 * one preset and over all of them. The first test here is the one that matters: it is
 * what makes that a fact rather than an intention, and it is why there is no risk of the
 * list and the verdict drifting apart.
 */

describe('the verdict and the list are one walk', () => {
    /**
     * For every preset on every kind of square, `possible` and "in the list" agree.
     *
     * Every kind of square rather than every square: the answer depends on the room type,
     * its size, the walls, and which address presets compete for the layout, so squares
     * agreeing on those are one case. That is 5 floors chosen to span office, retail,
     * residential, civic and industrial, and every distinct square in them against all
     * 310 presets -- around a quarter of a million verdicts.
     */
    test('possible is exactly what the list contains', async () => {
        const names = furniturePresetNames(chain);
        expect(names).toHaveLength(310);

        let checked = 0;
        let possible = 0;

        for (const name of [
            'Eden_OfficeFloor01', 'CityHall_GroundFloor', 'Tenement_MainFloor1',
            'ChemPlantGroundFloor1', 'Hotel_GroundFloor',
        ]) {
            const model = await blueprint(name);

            const seen = new Set();
            for (const [position, node] of model.nodes.entries()) {
                if (!node) continue;

                const x = position % 21;
                const y = Math.floor(position / 21);

                const at = furnitureAt(chain, model, x, y);
                if (!at || at.reason) continue;

                // A sample rather than every square, and it is a sample now rather than
                // the exhaustive sweep it once was: this key used to be everything the
                // walk read, and since the wall rules landed the walk reads the floor
                // three squares out in every direction. Adding the four edges keeps the
                // sample varied where it matters most; it does not make it complete.
                //
                // What this test is for survives that. It asserts the list and the verdict
                // are one walk, which is a property of any square either is asked about --
                // a disagreement would not be hiding on the squares this skips.
                const kind = JSON.stringify([at.roomType, at.roomSize, at.walls,
                    at.groups.map((group) => group.address),
                    [getWall(model, x, y, AXIS_X)?.preset ?? null,
                        getWall(model, x - 1, y, AXIS_X)?.preset ?? null,
                        getWall(model, x, y, AXIS_Y)?.preset ?? null,
                        getWall(model, x, y - 1, AXIS_Y)?.preset ?? null]]);

                if (seen.has(kind)) continue;
                seen.add(kind);

                for (const preset of names) {
                    const explained = explainFurniture(chain, model, x, y, preset);

                    for (const [index, group] of explained.groups.entries()) {
                        const listed = at.groups[index].classes
                            .some((row) => row.presets.some((entry) => entry.name === preset));

                        expect(group.verdict === 'possible', `${preset} in ${group.address}`)
                            .toBe(listed);

                        checked++;
                        if (listed) possible++;
                    }
                }
            }
        }

        // Guards against the whole thing passing because nothing was compared, and
        // against it passing because everything came back the same way. A floor rather
        // than a pinned count: this one is about how much the test covers, not about the
        // game's data, and it runs about 60,000 as it stands.
        expect(checked).toBeGreaterThan(50_000);
        expect(possible).toBeGreaterThan(0);
        expect(possible).toBeLessThan(checked);
    }, 60_000);

    test('a possible verdict names the slot classes the list files it under', async () => {
        const model = await blueprint('Eden_OfficeFloor01');
        const explained = explainFurniture(chain, model, 3, 11, 'OfficeCubicle');
        const [office] = explained.groups;

        expect(office.verdict).toBe('possible');
        expect(office.classes).toEqual(['1x1OfficeCubicle']);

        // Which is the row the list puts it in.
        const [listed] = furnitureAt(chain, model, 3, 11).groups;
        const row = listed.classes.find((entry) => entry.name === '1x1OfficeCubicle');
        expect(row.presets.map((preset) => preset.name)).toContain('OfficeCubicle');
    });
});


describe('the reason is the first gate that says no', () => {
    /**
     * Every stage, against a real square of a base game floor.
     *
     * The reasons are asserted in full rather than by stage alone. They are read by
     * someone deciding what to change, so the values in them -- which filters, which
     * class, how many walls -- are the whole of what makes them worth showing.
     */
    const office = (x, y, preset) => blueprint('Eden_OfficeFloor01')
        .then((model) => explainFurniture(chain, model, x, y, preset));

    test('address type, before anything about the room', async () => {
        const [group] = (await office(3, 11, 'TelephoneBooth')).groups;

        expect(group.stage).toBe('addressType');
        expect(group.reason).toBe('It is limited to AmericanDiner, CityHallLobby, FastFood, '
            + 'ChineseEatery, GamblingDen, Ballroom and Bar, and this unit would be HighriseOffice.');
    });

    test('room class', async () => {
        const [group] = (await office(3, 11, '24HrSign')).groups;

        expect(group.stage).toBe('roomClass');
        expect(group.reason)
            .toBe('Its room filters (Diner, Launderette and Supermarket) do not cover OfficeSpace.');
    });

    test('room size', async () => {
        const model = await blueprint('CityHall_FirstFloor');
        const [group] = explainFurniture(chain, model, 9, 3, 'MarblePillar').groups;

        expect(group.stage).toBe('roomSize');
        expect(group.reason)
            .toBe('It needs a room of at least 8 squares, and this CorporateLobby has 6.');
    });

    test('no cluster here has a slot it could fill', async () => {
        // Second group: the same square read as a Laboratory rather than an office.
        const [, lab] = (await office(3, 11, 'Blinds')).groups;

        expect(lab.stage).toBe('cluster');
        expect(lab.reason).toBe('Clusters are placeable in Laboratory rooms, but none of the 36 '
            + 'slot classes they put down is its class 1x1WindowPiece. WindowDecor would put down '
            + 'a 1x1WindowPiece slot, but is placeable only in the rooms the WindowDecor filter '
            + 'names. Add Laboratory to the roomClasses of that filter, or add a filter naming '
            + 'Laboratory to that cluster\'s allowedRoomFilters.');
    });

    /**
     * The guess is the last resort, and naming the carrier means it is never reached.
     *
     * A laboratory puts down 36 slot classes and none is named like a window, so `sharedPrefix`
     * would have offered nothing here even if asked -- which was the old assertion. What this
     * pins now is that it is not asked: a cluster carries `1x1WindowPiece` and can be named, so
     * the reason ends in an edit rather than in a resemblance.
     *
     * The cluster and the filter are both called `WindowDecor`, which is why the sentence says
     * "the rooms the WindowDecor filter names" rather than "WindowDecor rooms". The reader has
     * two assets of one name to tell apart and the sentence has to do it for them.
     */
    test('a room whose carrier can be named is never offered a guess', async () => {
        const [, lab] = (await office(3, 11, 'Blinds')).groups;

        expect(lab.reason).toContain('WindowDecor would put down a 1x1WindowPiece slot');
        expect(lab.reason).not.toMatch(/nearest|Those are|mod's own/);
    });

    test('the square itself', async () => {
        const [group] = (await office(4, 12, 'AlarmSiren')).groups;

        expect(group.stage).toBe('square');
        expect(group.reason).toBe('Its slot class 1x1AlarmSiren needs a square touching at '
            + 'least 1 wall, and this one has 0 walls.');
    });

    /**
     * The order is the point, not merely the reasons.
     *
     * `LargeBookcase` fails the room filter *and* has no office cluster to sit in *and*
     * needs a wall. The first is why the other two are true, and is the one an author can
     * act on -- the bookcase office mod exists because of exactly this gate. Reporting
     * the deepest failure, or all of them, would bury it.
     */
    test('a preset failing several gates is answered by the first', async () => {
        const middle = (await office(4, 12, 'LargeBookcase')).groups[0];
        const corner = (await office(3, 11, 'LargeBookcase')).groups[0];

        for (const group of [middle, corner]) {
            expect(group.stage).toBe('roomClass');
            expect(group.reason).toBe('Its room filters (GeneralFurnishing, PawnShop and '
                + 'LoanShark) do not cover OfficeSpace.');
        }
    });

    test('a preset the reference data has never heard of', async () => {
        const [group] = (await office(3, 11, 'MyModsSofa')).groups;

        expect(group.verdict).toBe('no');
        expect(group.stage).toBe('unknown');
        expect(group.reason).toBe('The base game has no furniture preset called MyModsSofa.');
    });
});


/**
 * Stage 4 in full, because it is the reason that misled somebody.
 *
 * "No furniture cluster placeable in a BankATMVestibuleRCP has a slot of its class" was read
 * as a room-filter failure -- no cluster reaches this room -- when clusters reached it fine
 * and only put down slots of other classes. The two states now say different things, and
 * the class-mismatch one names what the room *does* put down, which no panel showed before:
 * a slot class nothing fills is counted in the group listing and never named there.
 *
 * Every case below a mod overlay is a real square of a base game floor, found by walking
 * all 93 blueprints, so the wording is asserted against data rather than a fixture that
 * assumes its own answer.
 */
describe('why a preset has no slot to sit in', () => {
    const asset = (type, name, raw, patch = false) => ({ type, name, file: name, patch, raw });

    const square = async (floor, x, y, preset, data = chain) =>
        explainFurniture(data, await blueprint(floor), x, y, preset);

    /**
     * The size gate, which is the one of the three with no edit at the end of it.
     *
     * A cluster wanting four squares cannot be let into a room of two by any filter, so the
     * reason quotes the number and stops. Offering a filter to widen here would be true of
     * the filter and useless to the reader: the cluster still would not place, and they would
     * have patched a shipped asset to find that out.
     */
    test('a carrier kept out by the room\'s size is not offered a filter to widen', async () => {
        const [group] = (await square('CityHall_GroundFloor', 6, 7, 'AlarmSwitch')).groups;

        expect(group.stage).toBe('cluster');
        expect(group.reason).toBe('Clusters are placeable in CorporateCorridoor rooms, but none '
            + 'of the 4 slot classes they put down is its class 1x1AlarmSwitch. '
            + 'AlarmSwitchAndSiren would put down a 1x1AlarmSwitch slot, but needs a room of at '
            + 'least 4 squares, and this CorporateCorridoor has 2.');

        expect(group.reason).not.toMatch(/allowedRoomFilters|roomClasses/);
    });

    /**
     * A cluster the game ships switched off, which is why `disable` sorts last of the three:
     * there is nothing the reader can do about it. It is still worth naming, because the
     * alternative is an author widening filters towards a cluster that would not place if
     * they succeeded.
     */
    test('a carrier that is disabled is named as disabled', async () => {
        const [group] = (await square('ChemPlantFloor1', 3, 12, 'IndustrialMachineLong')).groups;

        expect(group.stage).toBe('cluster');
        expect(group.reason).toBe('Clusters are placeable in Industrial rooms, but none of the 41 '
            + 'slot classes they put down is its class 3x1IndustrialMachine. Machinery03 would '
            + 'put down a 3x1IndustrialMachine slot, but is disabled and places nowhere at all.');
    });

    /**
     * Both ends of the fix, drawn from the mod rather than from the base game.
     *
     * `AlarmSwitch` has two carriers here: the shipped `AlarmSwitchAndSiren`, which this room
     * is too small for, and the mod's own cluster, which is only kept out by its filters. The
     * filter gate wins -- it is the one with an edit behind it -- so the mod's cluster is what
     * gets named, over a base game cluster that fails a gate the reader cannot argue with.
     *
     * The second half of the fix then names `MyCorridoorFilter` rather than describing a
     * filter in the abstract, because the mod has one that already reaches this room. That is
     * the whole edit inside assets the author owns, with nothing shipped patched.
     */
    test('a mod\'s own carrier and filter are the two ends of the fix it is offered', async () => {
        const merged = overlayChain(chain, [
            asset('RoomTypeFilter', 'MyCorridoorFilter', {
                presetName: 'MyCorridoorFilter',
                fileType: 'RoomTypeFilter',
                roomClasses: ['REF:RoomClassPreset|CorporateCorridoor'],
            }),
            asset('FurnitureCluster', 'MyAlarmCluster', {
                presetName: 'MyAlarmCluster',
                fileType: 'FurnitureCluster',
                // A filter that does not reach this room, which is the mistake being reported.
                allowedRoomFilters: ['REF:RoomTypeFilter|Diner'],
                minimumRoomSize: 0,
                clusterElements: [{ furnitureClass: 'REF:FurnitureClass|1x1AlarmSwitch' }],
            }),
        ]);

        const [group] = (await square(
            'CityHall_GroundFloor', 6, 7, 'AlarmSwitch', merged)).groups;

        expect(group.stage).toBe('cluster');
        expect(group.reason).toContain('MyAlarmCluster would put down a 1x1AlarmSwitch slot, but '
            + 'is placeable only in the rooms the Diner filter names. Add CorporateCorridoor to '
            + 'the roomClasses of that filter, or add the MyCorridoorFilter filter to that '
            + 'cluster\'s allowedRoomFilters.');

        // The shipped carrier loses to the mod's, and the size it wants is not mentioned:
        // one gate, one instruction.
        expect(group.reason).not.toMatch(/AlarmSwitchAndSiren|squares/);
    });

    /**
     * A `.sodso.json` written from scratch gets `[]` from the game's own defaults, so this
     * is an unstated field rather than an exotic state. `OpenSign` is the base game's one
     * example, which is what makes it assertable here.
     */
    test('a preset listing no classes at all is told so outright', async () => {
        const [group] = (await square('ChemPlantGroundFloor1', 15, 9, 'OpenSign')).groups;

        expect(group.stage).toBe('cluster');
        expect(group.reason)
            .toBe('It lists no furniture classes at all, so there is no slot it could ever fill.');
    });

    /**
     * The state the old wording claimed and never meant.
     *
     * No base game floor reaches it -- the room classes no cluster targets are the ones no
     * `RoomTypeFilter` names either, so every preset fails at stage 2 first -- so it takes a
     * mod that opens a filter onto such a class. Which is exactly how an author would reach
     * it: a room filter widened to a class nothing furnishes.
     */
    test('a room no cluster reaches at all is a different sentence', async () => {
        const merged = overlayChain(chain, [
            asset('RoomTypeFilter', 'Atrium', {
                presetName: 'Atrium',
                fileType: 'RoomTypeFilter',
                roomClasses: ['REF:RoomClassPreset|Atrium'],
            }, true),
            asset('FurniturePreset', 'MyAtriumStatue', {
                presetName: 'MyAtriumStatue',
                fileType: 'FurniturePreset',
                classes: ['REF:FurnitureClass|My1x1Statue'],
                allowedRoomFilters: ['REF:RoomTypeFilter|Atrium'],
                minimumRoomSize: 0,
            }),
        ]);

        const [group] = (await square(
            'CityHall_FirstFloor', 9, 6, 'MyAtriumStatue', merged)).groups;

        expect(group.roomClass).toBe('Atrium');
        expect(group.stage).toBe('cluster');
        expect(group.reason).toBe('No furniture cluster is placeable in Atrium rooms, so nothing '
            + 'is furnished there at all.');
    });

    /**
     * A room whose clusters put down one slot class, which is the shape a mod's own small
     * room is usually in -- one cluster, one element -- and the case the ATM vestibule this
     * was written for was in. Both halves of the head go singular, and neither says "none of
     * the 1 slot classes" of a set of one.
     *
     * The carriers are the base game's two ATM clusters, between them allowing seven filters
     * and none naming `Atrium`, which is over `NAMED_FILTERS` -- so the reason counts the
     * filters rather than listing them, and the edit points at the set instead of at one.
     */
    test('a room with a single slot class reads as one thing, not as a list', async () => {
        const merged = overlayChain(chain, [
            asset('RoomTypeFilter', 'Atrium', {
                presetName: 'Atrium',
                fileType: 'RoomTypeFilter',
                roomClasses: ['REF:RoomClassPreset|Atrium'],
            }, true),
            asset('FurnitureClass', 'FreestandingATMBankFC', {
                presetName: 'FreestandingATMBankFC',
                fileType: 'FurnitureClass',
                minimumZeroNodeWallCount: 0,
            }),
            asset('FurnitureCluster', 'MyATMCluster', {
                presetName: 'MyATMCluster',
                fileType: 'FurnitureCluster',
                allowedRoomFilters: ['REF:RoomTypeFilter|Atrium'],
                minimumRoomSize: 0,
                clusterElements: [{ furnitureClass: 'REF:FurnitureClass|FreestandingATMBankFC' }],
            }),
            asset('FurniturePreset', 'FreestandingATM', {
                allowedRoomFilters: ['REF:RoomTypeFilter|Atrium'],
                minimumRoomSize: 0,
            }, true),
        ]);

        const [group] = (await square(
            'CityHall_FirstFloor', 9, 6, 'FreestandingATM', merged)).groups;

        expect(group.stage).toBe('cluster');
        expect(group.reason).toBe('Clusters are placeable in Atrium rooms, but the one slot class '
            + 'they put down is not its class 1x1FreestandingATM. 2_FreestandingATMStreet and '
            + 'FreestandingATM would put down a slot it could fill, but are placeable only in '
            + 'rooms named by 7 filters, none of which names Atrium. Add Atrium to the roomClasses '
            + 'of one of those filters, or add the Atrium filter to those clusters\' '
            + 'allowedRoomFilters.');
    });

    /**
     * Placeable clusters whose elements name no class. Nothing in the base game is in this
     * state, and a mod reaches it by writing `clusterElements` without a `furnitureClass`
     * on any of them -- which is why `clusterCount` is counted rather than inferred from an
     * empty slot set, that being the one thing an empty slot set cannot tell apart.
     */
    test('clusters that put down no slots are not clusters that are absent', async () => {
        const merged = overlayChain(chain, [
            asset('RoomTypeFilter', 'Atrium', {
                presetName: 'Atrium',
                fileType: 'RoomTypeFilter',
                roomClasses: ['REF:RoomClassPreset|Atrium'],
            }, true),
            asset('FurnitureCluster', 'MyEmptyCluster', {
                presetName: 'MyEmptyCluster',
                fileType: 'FurnitureCluster',
                allowedRoomFilters: ['REF:RoomTypeFilter|Atrium'],
                minimumRoomSize: 0,
                clusterElements: [{ importantToCluster: true }],
            }),
            asset('FurniturePreset', 'MyAtriumStatue', {
                presetName: 'MyAtriumStatue',
                fileType: 'FurniturePreset',
                classes: ['REF:FurnitureClass|My1x1Statue'],
                allowedRoomFilters: ['REF:RoomTypeFilter|Atrium'],
                minimumRoomSize: 0,
            }),
        ]);

        const [group] = (await square(
            'CityHall_FirstFloor', 9, 6, 'MyAtriumStatue', merged)).groups;

        expect(group.stage).toBe('cluster');
        expect(group.reason).toBe('The one cluster placeable in Atrium rooms puts down no '
            + 'furniture slots at all.');
    });

    /**
     * Both classes named, because either would have done and neither is the one to add.
     *
     * Four clusters carry them and all four fail the same gate, which is what `NAMED_CLUSTERS`
     * is for: two by name and the rest counted. The filters are unioned over all four rather
     * than over the two named -- "placeable only in these rooms" is a claim about every
     * cluster the sentence refers to, and the two it does not name are blocked by the same
     * pair of filters.
     */
    test('a preset with several classes is asked about all of them', async () => {
        const [group] = (await square('ChemPlantFloor1', 3, 15, 'LaserGrid')).groups;

        expect(group.stage).toBe('cluster');
        expect(group.reason).toBe('Clusters are placeable in PrivateOffice rooms, but none of the '
            + '37 slot classes they put down is any of its classes (1x1LaserGridR and '
            + '1x1LaserGridL). LaserGridLCorporate, LaserGridLResidential and 2 other clusters '
            + 'would put down a slot it could fill, but are placeable only in the rooms the '
            + 'LaserGridsCorporate and LaserGridsResidential filters name. Add PrivateOffice to '
            + 'the roomClasses of one of those filters, or add a filter naming PrivateOffice to '
            + 'those clusters\' allowedRoomFilters.');
    });

    /**
     * The base game arguing with itself, and the case this was written for.
     *
     * `SecurityCamera` is `Everywhere`, and the four clusters carrying its two slot classes
     * are not -- between them they reach only the rooms `Alarms`, `Bar` and `Diner` name. So
     * a preset that passes every room gate has nowhere to sit in a living room, with no mod
     * involved, which is what makes this assertable without a fixture.
     *
     * It pins the union too: the filters are collected over all four carriers, not the two
     * named, because `SecurityCameraLeftCornerEatery` is one of the named pair and `Alarms`
     * belongs to the two that are only counted.
     */
    test('a preset the base game itself gives no slot names the clusters that would', async () => {
        const [group] = (await square('Eden_DormFloor1', 3, 3, 'SecurityCamera')).groups;

        expect(group.roomClass).toBe('LivingRoom');
        expect(group.stage).toBe('cluster');
        expect(group.reason).toBe('Clusters are placeable in LivingRoom rooms, but none of the 62 '
            + 'slot classes they put down is any of its classes (1x1SecurityCameraRightCorner and '
            + '1x1SecurityCameraLeftCorner). SecurityCameraLeftCorner, '
            + 'SecurityCameraLeftCornerEatery and 2 other clusters would put down a slot it could '
            + 'fill, but are placeable only in the rooms the Alarms, Bar and Diner filters name. '
            + 'Add LivingRoom to the roomClasses of one of those filters, or add a filter naming '
            + 'LivingRoom to those clusters\' allowedRoomFilters.');
    });

    /**
     * A class no cluster anywhere puts down, where the instruction is the opposite one.
     *
     * `1x1SupermarketShelvingSign` is the only one of the game's 262 classes that no cluster
     * element names, and `SupermarketSignStarch` and `SupermarketSignSynthBeef` are the two
     * presets left standing on it. No filter reaches a cluster that does not exist, so an
     * author told to widen one would work at it forever -- the reason says outright that what
     * is missing is a cluster.
     *
     * This is also the one path where `slotHint` still runs, and the case that earns it. With
     * no cluster to open, the nearest slot the room *does* put down is the whole lead, and
     * `sharedPrefix` finds `1x1SupermarketShelvingBackward` -- which is almost certainly the
     * class the preset should have listed.
     */
    test('a class nothing anywhere carries is told to want a cluster, not a filter', async () => {
        const [group] = (await square(
            'Eden_GroundFloor', 14, 3, 'SupermarketSignStarch')).groups;

        expect(group.roomClass).toBe('Chemist');
        expect(group.stage).toBe('cluster');
        expect(group.reason).toBe('Clusters are placeable in Chemist rooms, but none of the 45 '
            + 'slot classes they put down is its class 1x1SupermarketShelvingSign. No cluster '
            + 'anywhere puts down that slot, so widening a filter would not help: what is missing '
            + 'is a cluster with an element of that class. The nearest by name is '
            + '1x1SupermarketShelvingBackward.');
    });

});


describe('a square with no answer for anything', () => {
    test('an outdoor square is one reason, not one per address preset', () => {
        const outside = hotel.nodes.findIndex((node) => node
            && hotel.addresses[node.addressIndex]?.layoutConfiguration === 'Outside');

        const explained = explainFurniture(
            chain, hotel, outside % 21, Math.floor(outside / 21), 'OfficeCubicle');

        expect(explained.groups).toEqual([]);
        expect(explained.reason).toMatch(/outdoor layout/);
        expect(explained.preset).toBe('OfficeCubicle');
    });

    test('nothing to explain against gives nothing', () => {
        expect(explainFurniture(null, hotel, 10, 10, 'OfficeCubicle')).toBeNull();
        expect(explainFurniture(chain, hotel, 99, 99, 'OfficeCubicle')).toBeNull();
    });
});


/**
 * The list, split into the mod's own and the base game's.
 *
 * What matters is the split, not the order within either half: both come off
 * `furniturePresetNames`, which is already sorted and already covered.
 */
describe('which presets are the mod\'s', () => {
    /** An asset as `readModAssets` reports one, without going near a folder. */
    const asset = (type, name, raw, patch = false) => ({ type, name, file: name, patch, raw });

    test('with no mod, everything is the base game\'s', () => {
        const sections = furniturePresetSections(chain);

        expect(sections.modded).toEqual([]);
        expect(sections.vanilla).toHaveLength(310);
        expect(sections.vanilla).toEqual(furniturePresetNames(chain));
    });

    test('a preset the mod adds is the mod\'s, and is still on the whole list', () => {
        const merged = overlayChain(chain, [
            asset('FurniturePreset', 'MyModsSofa', { name: 'MyModsSofa' }),
        ]);

        const sections = furniturePresetSections(merged);

        expect(sections.modded).toEqual(['MyModsSofa']);
        expect(sections.vanilla).toHaveLength(310);
        expect(sections.vanilla).not.toContain('MyModsSofa');

        // The two sections are the list, so nothing can be offered twice or dropped.
        expect([...sections.modded, ...sections.vanilla].sort())
            .toEqual(furniturePresetNames(merged));
    });

    /**
     * A patch changes a shipped preset's values without adding a name. The name is the
     * base game's; the values are not, and the values are the whole reason this list is
     * being read -- so the section that tells an author the answer depends on their own
     * file is the honest one.
     */
    test('a shipped preset the mod patches counts as the mod\'s', () => {
        const merged = overlayChain(chain, [
            asset('FurniturePreset', 'LargeBookcase', { minimumRoomSize: 1 }, true),
        ]);

        const sections = furniturePresetSections(merged);

        expect(sections.modded).toEqual(['LargeBookcase']);
        expect(sections.vanilla).not.toContain('LargeBookcase');
        expect(sections.vanilla).toHaveLength(309);
    });

    test('assets of other types are not furniture presets', () => {
        const merged = overlayChain(chain, [
            asset('FurnitureCluster', 'MyModsCluster', { name: 'MyModsCluster' }),
            asset('AddressPreset', 'MyModsOffice', { name: 'MyModsOffice' }),
        ]);

        expect(furniturePresetSections(merged).modded).toEqual([]);
    });

    /**
     * Cached on the data, like the names are. The status column is redrawn on every
     * pointer move and the panel rebuilds its control whenever this identity changes, so
     * a fresh object per call would rebuild a select over 310 names per pixel of a drag.
     */
    test('the same object for the same data, and a new one after a merge', () => {
        expect(furniturePresetSections(chain)).toBe(furniturePresetSections(chain));

        const merged = overlayChain(chain, []);
        expect(furniturePresetSections(merged)).not.toBe(furniturePresetSections(chain));
    });

    test('nothing to split gives empty sections rather than throwing', () => {
        expect(furniturePresetSections(null)).toEqual({ modded: [], vanilla: [] });
    });
});


/**
 * Problems in the mod's own assets, which are true of the mod rather than of a square.
 *
 * Two failure modes from the placement checklist: an element that can never be attempted,
 * and a cluster that will turn up in every room of its class in the city. Neither is
 * reported by the game at run time, and neither depends on where the pointer is.
 *
 * The base game is the control throughout. It ships two clusters holding a zero chance
 * and sixteen elements holding a deliberate fractional one, so "warns about the mod's
 * assets and only the mod's" and "0 is a defect, 0.9 is not" are both checkable against
 * real data rather than against a fixture that assumes the answer.
 */
describe('problems in the mod\'s own assets', () => {
    const asset = (type, name, raw, patch = false) => ({ type, name, file: name, patch, raw });

    /** A cluster file with one element, stated the way a mod would write it. */
    const clusterWith = (element) => ({
        presetName: 'MyDeskCluster',
        fileType: 'FurnitureCluster',
        allowedRoomFilters: ['REF:RoomTypeFilter|CorporateLobby'],
        clusterElements: [{ furnitureClass: 'REF:FurnitureClass|My1x1Desk', ...element }],
    });

    const warn = (assets) => clusterWarnings(overlayChain(chain, assets));

    test('with no mod selected there is nothing to report', () => {
        expect(clusterWarnings(chain)).toEqual([]);
        expect(clusterWarnings(overlayChain(chain, []))).toEqual([]);
        expect(clusterWarnings(null)).toEqual([]);
    });

    /**
     * The control that matters most. `2_ArmchairFacingTVWithTable` and
     * `3_FacingArmchairs` each ship an element at chance 0, so a check that looked at
     * every cluster rather than the mod's would open with two complaints about the base
     * game on a page where the author has done nothing wrong.
     */
    test('the base game\'s own zero-chance elements are not the author\'s problem', () => {
        const shipped = ['2_ArmchairFacingTVWithTable', '3_FacingArmchairs'];

        for (const name of shipped) {
            const element = chain.clusters[name].elements.find((entry) => entry.chance === 0);
            expect(element, `${name} should still ship a zero chance`).toBeDefined();
        }

        // A mod that adds something unrelated does not inherit the complaint.
        const warnings = warn([asset('FurniturePreset', 'MySofa', { presetName: 'MySofa' })]);
        expect(warnings.filter((entry) => shipped.includes(entry.cluster))).toEqual([]);
    });

    test('a zero chance on a required element fails the whole cluster', () => {
        const warnings = warn([asset('FurnitureCluster', 'MyDeskCluster',
            clusterWith({ chanceOfPlacementAttempt: 0, importantToCluster: true }))]);

        expect(warnings).toHaveLength(1);
        expect(warnings[0].severity).toBe('blocks');
        expect(warnings[0].cluster).toBe('MyDeskCluster');
        expect(warnings[0].text).toContain('the whole cluster fails');
        expect(warnings[0].text).toContain('My1x1Desk');
    });

    test('a zero chance on an optional element only thins the cluster', () => {
        const warnings = warn([asset('FurnitureCluster', 'MyDeskCluster',
            clusterWith({ chanceOfPlacementAttempt: 0, importantToCluster: false }))]);

        expect(warnings).toHaveLength(1);
        expect(warnings[0].severity).toBe('degrades');
        expect(warnings[0].text).toContain('never attempted');
        expect(warnings[0].text).not.toContain('whole cluster');
    });

    /**
     * 16 of the base game's 18 stated chances are 0.5, 0.8 or 0.9. Treating "not 1" as
     * the defect would call every one of them broken, so the rule is "0" and nothing else.
     */
    test('a deliberate fractional chance is not a defect', () => {
        for (const chance of [0.5, 0.8, 0.9, 1]) {
            const warnings = warn([asset('FurnitureCluster', 'MyDeskCluster',
                clusterWith({ chanceOfPlacementAttempt: chance, importantToCluster: true }))]);

            expect(warnings, `chance ${chance}`).toEqual([]);
        }
    });

    /**
     * Whether an absent field deserialises to 0 or to 1 is not something this repo can
     * establish, and reading it as 0 would report every hand-written minimal element as
     * broken. Only a stated 0 counts -- see `readElement`.
     */
    test('an element that omits the field is left alone', () => {
        const warnings = warn([asset('FurnitureCluster', 'MyDeskCluster',
            clusterWith({ importantToCluster: true }))]);

        expect(warnings).toEqual([]);
    });

    test('a zero scale places the furniture at no size at all', () => {
        const warnings = warn([asset('FurnitureCluster', 'MyDeskCluster',
            clusterWith({ localScale: { x: 0, y: 0, z: 0 } }))]);

        expect(warnings).toHaveLength(1);
        expect(warnings[0].severity).toBe('blocks');
        expect(warnings[0].text).toContain('no size at all');
    });

    test('a scale that is merely not 1 is left alone', () => {
        const warnings = warn([asset('FurnitureCluster', 'MyDeskCluster',
            clusterWith({ localScale: { x: 1, y: 0.5, z: 1 } }))]);

        expect(warnings).toEqual([]);
    });

    /**
     * The city-wide case, which is the one that produced 34 desks across 27 unrelated
     * rooms. Room filters are city-wide, so the gate has to go on the preset.
     */
    describe('a cluster that reaches every room of its class', () => {
        const deskCluster = asset('FurnitureCluster', 'MyDeskCluster', {
            presetName: 'MyDeskCluster',
            fileType: 'FurnitureCluster',
            allowedRoomFilters: ['REF:RoomTypeFilter|CorporateLobby'],
            clusterElements: [{
                furnitureClass: 'REF:FurnitureClass|My1x1Desk',
                chanceOfPlacementAttempt: 1,
            }],
        });

        const desk = (extra) => asset('FurniturePreset', 'MyDesk', {
            presetName: 'MyDesk',
            fileType: 'FurniturePreset',
            classes: ['REF:FurnitureClass|My1x1Desk'],
            ...extra,
        });

        test('an ungated preset filling its slots is reported', () => {
            const warnings = warn([deskCluster, desk({})]);

            expect(warnings).toHaveLength(1);
            expect(warnings[0].severity).toBe('degrades');
            expect(warnings[0].text).toContain('gated only by room filters');
            expect(warnings[0].text).toContain('CorporateLobby');
            expect(warnings[0].text).toContain('MyDesk');
        });

        test('confining the preset to an address type settles it', () => {
            expect(warn([deskCluster, desk({
                onlyAllowInFollowing: true,
                allowedInAddressesOfType: ['REF:AddressPreset|CityHallLobby'],
            })])).toEqual([]);
        });

        test('confining it to a building settles it too', () => {
            expect(warn([deskCluster, desk({
                OnlyAllowInBuildings: true,
                allowedInBuildings: ['REF:BuildingPreset|CityBank'],
            })])).toEqual([]);
        });

        /**
         * A cluster arranging the base game's furniture is city-wide as well, but the
         * advice would be to gate the base game's presets, which is not something an
         * author should be told to do. Silent rather than unhelpful.
         */
        test('a cluster of nothing but shipped furniture is not reported', () => {
            const shipped = asset('FurnitureCluster', 'MyBookcaseCluster', {
                presetName: 'MyBookcaseCluster',
                fileType: 'FurnitureCluster',
                allowedRoomFilters: ['REF:RoomTypeFilter|CorporateLobby'],
                clusterElements: [{
                    furnitureClass: `REF:FurnitureClass|${chain.furniture.LargeBookcase.classes[0]}`,
                    chanceOfPlacementAttempt: 1,
                }],
            });

            expect(warn([shipped])).toEqual([]);
        });
    });

    test('what blocks comes before what merely degrades', () => {
        const warnings = warn([
            asset('FurnitureCluster', 'MyThinCluster', {
                presetName: 'MyThinCluster',
                fileType: 'FurnitureCluster',
                allowedRoomFilters: ['REF:RoomTypeFilter|CorporateLobby'],
                clusterElements: [{
                    furnitureClass: 'REF:FurnitureClass|My1x1Lamp',
                    chanceOfPlacementAttempt: 0,
                    importantToCluster: false,
                }],
            }),
            asset('FurnitureCluster', 'MyDeadCluster', {
                presetName: 'MyDeadCluster',
                fileType: 'FurnitureCluster',
                allowedRoomFilters: ['REF:RoomTypeFilter|CorporateLobby'],
                clusterElements: [{
                    furnitureClass: 'REF:FurnitureClass|My1x1Desk',
                    chanceOfPlacementAttempt: 0,
                    importantToCluster: true,
                }],
            }),
        ]);

        expect(warnings.map((entry) => entry.severity)).toEqual(['blocks', 'degrades']);
        expect(warnings[0].cluster).toBe('MyDeadCluster');
    });

    test('the same list for the same data, and a fresh one after a merge', () => {
        const merged = overlayChain(chain, []);

        expect(clusterWarnings(merged)).toBe(clusterWarnings(merged));
        expect(clusterWarnings(merged)).not.toBe(clusterWarnings(overlayChain(chain, [])));
    });
});
